/** Audited baseline evidence. A new registry entry is partial until it has a record. */
export interface CertificationEvidence {
  sourceId: string;
  algorithm: string;
  strategy: string;
  oracle: string;
  edgeCases: string;
  browser: string;
}

const baselineBrowser = "tests/e2e/all-problem-routes.spec.ts";
const baselineEdges = "tests/representative-problems.test.ts";

export const certificationEvidence: Record<string, CertificationEvidence> = {
  "weird-algorithm": {
    sourceId: "1068",
    algorithm: "odd/even recurrence",
    strategy: "generic",
    oracle: "tests/introductory-problems.test.ts:weird-algorithm",
    edgeCases: "tests/introductory-problems.test.ts:weird-algorithm",
    browser: baselineBrowser,
  },
  "missing-number": {
    sourceId: "1083",
    algorithm: "arithmetic sum difference",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:missing-number",
    edgeCases: "tests/introductory-problems.test.ts:missing-number",
    browser: baselineBrowser,
  },
  repetitions: {
    sourceId: "1069",
    algorithm: "run-length scan",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:repetitions",
    edgeCases: "tests/introductory-problems.test.ts:repetitions",
    browser: baselineBrowser,
  },
  permutations: {
    sourceId: "1070",
    algorithm: "parity construction",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:permutations",
    edgeCases: "tests/introductory-problems.test.ts:permutations",
    browser: baselineBrowser,
  },
  "bit-strings": {
    sourceId: "1617",
    algorithm: "modular doubling",
    strategy: "number-theory",
    oracle: "tests/introductory-problems.test.ts:bit-strings",
    edgeCases: "tests/introductory-problems.test.ts:bit-strings",
    browser: baselineBrowser,
  },
  "trailing-zeros": {
    sourceId: "1618",
    algorithm: "factor-of-five counting",
    strategy: "generic",
    oracle: "tests/introductory-problems.test.ts:trailing-zeros",
    edgeCases: "tests/introductory-problems.test.ts:trailing-zeros",
    browser: baselineBrowser,
  },
  "coin-piles": {
    sourceId: "1754",
    algorithm: "linear Diophantine invariant",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:coin-piles",
    edgeCases: "tests/introductory-problems.test.ts:coin-piles",
    browser: baselineBrowser,
  },
  "two-knights": {
    sourceId: "1072",
    algorithm: "combinatorial complement counting",
    strategy: "geometry",
    oracle: "tests/introductory-problems.test.ts:two-knights",
    edgeCases: "tests/introductory-problems.test.ts:two-knights",
    browser: baselineBrowser,
  },
  "two-sets": {
    sourceId: "1092",
    algorithm: "descending greedy partition",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:two-sets",
    edgeCases: "tests/introductory-problems.test.ts:two-sets",
    browser: baselineBrowser,
  },
  "number-spiral": {
    sourceId: "1071",
    algorithm: "square-layer parity formula",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:number-spiral",
    edgeCases: "tests/introductory-problems.test.ts:number-spiral",
    browser: baselineBrowser,
  },
  "increasing-array": {
    sourceId: "1094",
    algorithm: "greedy monotone scan",
    strategy: "array",
    oracle: "tests/problem-certification.test.ts:increasing-array-oracle",
    edgeCases: "tests/code-runtime.test.ts",
    browser: baselineBrowser,
  },
  labyrinth: {
    sourceId: "1193",
    algorithm: "breadth-first search",
    strategy: "bfs",
    oracle: "tests/correctness.test.ts:labyrinth",
    edgeCases: "tests/simulation.test.ts",
    browser: baselineBrowser,
  },
  "message-route": {
    sourceId: "1667",
    algorithm: "breadth-first search",
    strategy: "bfs",
    oracle: "tests/correctness.test.ts:message-route",
    edgeCases: "tests/simulation.test.ts",
    browser: baselineBrowser,
  },
  "tree-diameter": {
    sourceId: "1131",
    algorithm: "two breadth-first searches",
    strategy: "tree",
    oracle: "tests/correctness.test.ts:tree-diameter",
    edgeCases: "tests/simulation.test.ts",
    browser: baselineBrowser,
  },
  "dice-combinations": {
    sourceId: "1633",
    algorithm: "one-dimensional dynamic programming",
    strategy: "dp",
    oracle: "tests/correctness.test.ts:dice-combinations",
    edgeCases: "tests/simulation.test.ts",
    browser: baselineBrowser,
  },
  "distinct-numbers": {
    sourceId: "1621",
    algorithm: "sort and scan",
    strategy: "sorting",
    oracle: "tests/representative-problems.test.ts:distinct-numbers",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "sum-of-two-values": {
    sourceId: "1640",
    algorithm: "sort and two pointers",
    strategy: "two-pointers",
    oracle: "tests/representative-problems.test.ts:sum-of-two-values",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "sliding-window-sum": {
    sourceId: "3220",
    algorithm: "sliding window",
    strategy: "sliding-window",
    oracle: "tests/representative-problems.test.ts:sliding-window-sum",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "factory-machines": {
    sourceId: "1620",
    algorithm: "binary search on answer",
    strategy: "binary-search",
    oracle: "tests/representative-problems.test.ts:factory-machines",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "static-range-sum": {
    sourceId: "1646",
    algorithm: "prefix sums",
    strategy: "range",
    oracle: "tests/representative-problems.test.ts:static-range-sum",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "dynamic-range-sum": {
    sourceId: "1648",
    algorithm: "Fenwick tree",
    strategy: "fenwick",
    oracle: "tests/representative-problems.test.ts:dynamic-range-sum",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "counting-rooms": {
    sourceId: "1192",
    algorithm: "depth-first flood fill",
    strategy: "dfs",
    oracle: "tests/representative-problems.test.ts:counting-rooms",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "shortest-routes-i": {
    sourceId: "1671",
    algorithm: "Dijkstra shortest path",
    strategy: "shortest-path",
    oracle: "tests/representative-problems.test.ts:shortest-routes-i",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  subordinates: {
    sourceId: "1674",
    algorithm: "tree postorder aggregation",
    strategy: "tree",
    oracle: "tests/representative-problems.test.ts:subordinates",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "road-construction": {
    sourceId: "1676",
    algorithm: "disjoint set union",
    strategy: "dsu",
    oracle: "tests/representative-problems.test.ts:road-construction",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "edit-distance": {
    sourceId: "1639",
    algorithm: "two-dimensional dynamic programming",
    strategy: "dp",
    oracle: "tests/representative-problems.test.ts:edit-distance",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "string-matching": {
    sourceId: "1753",
    algorithm: "Knuth-Morris-Pratt",
    strategy: "strings",
    oracle: "tests/representative-problems.test.ts:string-matching",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "chessboard-and-queens": {
    sourceId: "1624",
    algorithm: "backtracking",
    strategy: "backtracking",
    oracle: "tests/representative-problems.test.ts:chessboard-and-queens",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  exponentiation: {
    sourceId: "1095",
    algorithm: "binary exponentiation",
    strategy: "number-theory",
    oracle: "tests/representative-problems.test.ts:exponentiation",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "polygon-area": {
    sourceId: "2191",
    algorithm: "shoelace formula",
    strategy: "geometry",
    oracle: "tests/representative-problems.test.ts:polygon-area",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
};
