/** Audited baseline evidence. A new registry entry is partial until it has a record. */
export interface CertificationEvidence {
  sourceId: string;
  algorithm: string;
  strategy: string;
  oracle: string;
  edgeCases: string;
  browser: string;
}

const baselineBrowser = "tests/e2e/all-problem-routes.spec.ts";
const baselineEdges = "tests/representative-problems.test.ts";

export const certificationEvidence: Record<string, CertificationEvidence> = {
  "round-trip": {
    sourceId: "1669",
    algorithm: "undirected DFS cycle reconstruction",
    strategy: "dfs",
    oracle: "tests/graph-wave-100.test.ts:round-trip",
    edgeCases: "tests/graph-wave-100.test.ts:round-trip",
    browser: baselineBrowser,
  },
  "planets-queries-i": {
    sourceId: "1750",
    algorithm: "functional-graph binary lifting",
    strategy: "generic",
    oracle: "tests/graph-wave-100.test.ts:planets-queries-i",
    edgeCases: "tests/graph-wave-100.test.ts:planets-queries-i",
    browser: baselineBrowser,
  },
  "planets-and-kingdoms": {
    sourceId: "1683",
    algorithm: "Kosaraju strongly connected components",
    strategy: "dfs",
    oracle: "tests/graph-wave-100.test.ts:planets-and-kingdoms",
    edgeCases: "tests/graph-wave-100.test.ts:planets-and-kingdoms",
    browser: baselineBrowser,
  },
  "cycle-finding": {
    sourceId: "1197",
    algorithm: "Bellman-Ford negative-cycle reconstruction",
    strategy: "generic",
    oracle: "tests/graph-wave-100.test.ts:cycle-finding",
    edgeCases: "tests/graph-wave-100.test.ts:cycle-finding",
    browser: baselineBrowser,
  },
  "flight-discount": {
    sourceId: "1195",
    algorithm: "two Dijkstra runs and coupon-edge scan",
    strategy: "shortest-path",
    oracle: "tests/graph-wave-100.test.ts:flight-discount",
    edgeCases: "tests/graph-wave-100.test.ts:flight-discount",
    browser: baselineBrowser,
  },
  investigation: {
    sourceId: "1202",
    algorithm: "Dijkstra shortest-path DAG counting",
    strategy: "shortest-path",
    oracle: "tests/graph-wave-100.test.ts:investigation",
    edgeCases: "tests/graph-wave-100.test.ts:investigation",
    browser: baselineBrowser,
  },
  "high-score": {
    sourceId: "1673",
    algorithm: "Bellman-Ford maximum score and positive-cycle reachability",
    strategy: "generic",
    oracle: "tests/graph-wave-100.test.ts:high-score",
    edgeCases: "tests/graph-wave-100.test.ts:high-score",
    browser: baselineBrowser,
  },
  "company-queries-ii": {
    sourceId: "1688",
    algorithm: "lowest common ancestor by binary lifting",
    strategy: "tree",
    oracle: "tests/tree-wave-100.test.ts:company-queries-ii",
    edgeCases: "tests/tree-wave-100.test.ts:company-queries-ii",
    browser: baselineBrowser,
  },
  "distance-queries": {
    sourceId: "1135",
    algorithm: "tree distance by binary lifting LCA",
    strategy: "tree",
    oracle: "tests/tree-wave-100.test.ts:distance-queries",
    edgeCases: "tests/tree-wave-100.test.ts:distance-queries",
    browser: baselineBrowser,
  },
  "finding-a-centroid": {
    sourceId: "2079",
    algorithm: "subtree sizes and centroid balance",
    strategy: "tree",
    oracle: "tests/tree-wave-100.test.ts:finding-a-centroid",
    edgeCases: "tests/tree-wave-100.test.ts:finding-a-centroid",
    browser: baselineBrowser,
  },
  "subtree-queries": {
    sourceId: "1137",
    algorithm: "Euler intervals and Fenwick sums",
    strategy: "fenwick",
    oracle: "tests/tree-wave-100.test.ts:subtree-queries",
    edgeCases: "tests/tree-wave-100.test.ts:subtree-queries",
    browser: baselineBrowser,
  },
  "distinct-colors": {
    sourceId: "1139",
    algorithm: "Euler sweep with latest-color Fenwick marks",
    strategy: "fenwick",
    oracle: "tests/tree-wave-100.test.ts:distinct-colors",
    edgeCases: "tests/tree-wave-100.test.ts:distinct-colors",
    browser: baselineBrowser,
  },
  "hotel-queries": {
    sourceId: "1143",
    algorithm: "first-fit segment maximum",
    strategy: "array",
    oracle: "tests/range-wave-100.test.ts:hotel-queries",
    edgeCases: "tests/range-wave-100.test.ts:hotel-queries",
    browser: baselineBrowser,
  },
  "list-removals": {
    sourceId: "1749",
    algorithm: "Fenwick order statistics",
    strategy: "fenwick",
    oracle: "tests/range-wave-100.test.ts:list-removals",
    edgeCases: "tests/range-wave-100.test.ts:list-removals",
    browser: baselineBrowser,
  },
  "prefix-sum-queries": {
    sourceId: "2166",
    algorithm: "segment tree maximum prefix monoid",
    strategy: "range",
    oracle: "tests/range-wave-100.test.ts:prefix-sum-queries",
    edgeCases: "tests/range-wave-100.test.ts:prefix-sum-queries",
    browser: baselineBrowser,
  },
  "pizzeria-queries": {
    sourceId: "2206",
    algorithm: "paired segment minima for distance transform",
    strategy: "array",
    oracle: "tests/range-wave-100.test.ts:pizzeria-queries",
    edgeCases: "tests/range-wave-100.test.ts:pizzeria-queries",
    browser: baselineBrowser,
  },
  "exponentiation-ii": {
    sourceId: "1712",
    algorithm: "nested modular binary exponentiation",
    strategy: "number-theory",
    oracle: "tests/mathematics-advanced.test.ts:exponentiation-ii",
    edgeCases: "tests/mathematics-advanced.test.ts:exponentiation-ii",
    browser: baselineBrowser,
  },
  "fibonacci-numbers": {
    sourceId: "1722",
    algorithm: "fast doubling Fibonacci",
    strategy: "number-theory",
    oracle: "tests/mathematics-advanced.test.ts:fibonacci-numbers",
    edgeCases: "tests/mathematics-advanced.test.ts:fibonacci-numbers",
    browser: baselineBrowser,
  },
  "counting-divisors": {
    sourceId: "1713",
    algorithm: "smallest-prime-factor divisor count",
    strategy: "generic",
    oracle: "tests/mathematics-advanced.test.ts:counting-divisors",
    edgeCases: "tests/mathematics-advanced.test.ts:counting-divisors",
    browser: baselineBrowser,
  },
  "common-divisors": {
    sourceId: "1081",
    algorithm: "descending divisor multiple counts",
    strategy: "generic",
    oracle: "tests/mathematics-advanced.test.ts:common-divisors",
    edgeCases: "tests/mathematics-advanced.test.ts:common-divisors",
    browser: baselineBrowser,
  },
  "binomial-coefficients": {
    sourceId: "1079",
    algorithm: "factorials and modular inverse",
    strategy: "number-theory",
    oracle: "tests/mathematics-advanced.test.ts:binomial-coefficients",
    edgeCases: "tests/mathematics-advanced.test.ts:binomial-coefficients",
    browser: baselineBrowser,
  },
  "creating-strings-ii": {
    sourceId: "1715",
    algorithm: "multinomial coefficient",
    strategy: "number-theory",
    oracle: "tests/mathematics-advanced.test.ts:creating-strings-ii",
    edgeCases: "tests/mathematics-advanced.test.ts:creating-strings-ii",
    browser: baselineBrowser,
  },
  "distributing-apples": {
    sourceId: "1716",
    algorithm: "stars-and-bars binomial",
    strategy: "number-theory",
    oracle: "tests/mathematics-advanced.test.ts:distributing-apples",
    edgeCases: "tests/mathematics-advanced.test.ts:distributing-apples",
    browser: baselineBrowser,
  },
  "point-location-test": {
    sourceId: "2189",
    algorithm: "signed cross-product orientation",
    strategy: "geometry",
    oracle: "tests/geometry-primitives.test.ts:point-location-test",
    edgeCases: "tests/geometry-primitives.test.ts:point-location-test",
    browser: baselineBrowser,
  },
  "line-segment-intersection": {
    sourceId: "2190",
    algorithm: "orientation straddle and collinear overlap",
    strategy: "geometry",
    oracle: "tests/geometry-primitives.test.ts:line-segment-intersection",
    edgeCases: "tests/geometry-primitives.test.ts:line-segment-intersection",
    browser: baselineBrowser,
  },
  "game-routes": {
    sourceId: "1681",
    algorithm: "topological route-count DP",
    strategy: "topological-sort",
    oracle: "tests/dag-routes.test.ts:game-routes",
    edgeCases: "tests/dag-routes.test.ts:game-routes",
    browser: baselineBrowser,
  },
  "longest-flight-route": {
    sourceId: "1680",
    algorithm: "topological longest-path DP",
    strategy: "topological-sort",
    oracle: "tests/dag-routes.test.ts:longest-flight-route",
    edgeCases: "tests/dag-routes.test.ts:longest-flight-route",
    browser: baselineBrowser,
  },
  "counting-towers": {
    sourceId: "2413",
    algorithm: "two-boundary-state tower DP",
    strategy: "dp",
    oracle: "tests/dynamic-advanced.test.ts:counting-towers",
    edgeCases: "tests/dynamic-advanced.test.ts:counting-towers",
    browser: baselineBrowser,
  },
  projects: {
    sourceId: "1140",
    algorithm: "weighted interval scheduling with binary search",
    strategy: "binary-search",
    oracle: "tests/dynamic-advanced.test.ts:projects",
    edgeCases: "tests/dynamic-advanced.test.ts:projects",
    browser: baselineBrowser,
  },
  "elevator-rides": {
    sourceId: "1653",
    algorithm: "lexicographic bitmask DP",
    strategy: "dp",
    oracle: "tests/dynamic-advanced.test.ts:elevator-rides",
    edgeCases: "tests/dynamic-advanced.test.ts:elevator-rides",
    browser: baselineBrowser,
  },
  "finding-borders": {
    sourceId: "1732",
    algorithm: "prefix-function border chain",
    strategy: "strings",
    oracle: "tests/string-algorithms.test.ts:finding-borders",
    edgeCases: "tests/string-algorithms.test.ts:finding-borders",
    browser: baselineBrowser,
  },
  "finding-periods": {
    sourceId: "1733",
    algorithm: "Z-function period test",
    strategy: "strings",
    oracle: "tests/string-algorithms.test.ts:finding-periods",
    edgeCases: "tests/string-algorithms.test.ts:finding-periods",
    browser: baselineBrowser,
  },
  "string-functions": {
    sourceId: "2107",
    algorithm: "Z-function and KMP prefix function",
    strategy: "strings",
    oracle: "tests/string-algorithms.test.ts:string-functions",
    edgeCases: "tests/string-algorithms.test.ts:string-functions",
    browser: baselineBrowser,
  },
  "word-combinations": {
    sourceId: "1731",
    algorithm: "trie-guided prefix counting DP",
    strategy: "dp",
    oracle: "tests/string-algorithms.test.ts:word-combinations",
    edgeCases: "tests/string-algorithms.test.ts:word-combinations",
    browser: baselineBrowser,
  },
  "static-range-minimum": {
    sourceId: "1647",
    algorithm: "sparse-table range minimum",
    strategy: "range",
    oracle: "tests/range-algorithms.test.ts:static-range-minimum",
    edgeCases: "tests/range-algorithms.test.ts:static-range-minimum",
    browser: baselineBrowser,
  },
  "dynamic-range-minimum": {
    sourceId: "1649",
    algorithm: "segment-tree point update and range minimum",
    strategy: "range",
    oracle: "tests/range-algorithms.test.ts:dynamic-range-minimum",
    edgeCases: "tests/range-algorithms.test.ts:dynamic-range-minimum",
    browser: baselineBrowser,
  },
  "range-xor-queries": {
    sourceId: "1650",
    algorithm: "prefix-XOR range cancellation",
    strategy: "range",
    oracle: "tests/range-algorithms.test.ts:range-xor-queries",
    edgeCases: "tests/range-algorithms.test.ts:range-xor-queries",
    browser: baselineBrowser,
  },
  "range-update-queries": {
    sourceId: "1651",
    algorithm: "Fenwick tree over difference array",
    strategy: "fenwick",
    oracle: "tests/range-algorithms.test.ts:range-update-queries",
    edgeCases: "tests/range-algorithms.test.ts:range-update-queries",
    browser: baselineBrowser,
  },
  "forest-queries": {
    sourceId: "1652",
    algorithm: "two-dimensional prefix sums",
    strategy: "range",
    oracle: "tests/range-algorithms.test.ts:forest-queries",
    edgeCases: "tests/range-algorithms.test.ts:forest-queries",
    browser: baselineBrowser,
  },
  "tree-distances-i": {
    sourceId: "1132",
    algorithm: "two diameter endpoint distance traversals",
    strategy: "tree",
    oracle: "tests/tree-algorithms.test.ts:tree-distances-i",
    edgeCases: "tests/tree-algorithms.test.ts:tree-distances-i",
    browser: baselineBrowser,
  },
  "tree-distances-ii": {
    sourceId: "1133",
    algorithm: "subtree sizes and distance-sum rerooting",
    strategy: "tree",
    oracle: "tests/tree-algorithms.test.ts:tree-distances-ii",
    edgeCases: "tests/tree-algorithms.test.ts:tree-distances-ii",
    browser: baselineBrowser,
  },
  "tree-matching": {
    sourceId: "1130",
    algorithm: "postorder two-state tree matching DP",
    strategy: "tree",
    oracle: "tests/tree-algorithms.test.ts:tree-matching",
    edgeCases: "tests/tree-algorithms.test.ts:tree-matching",
    browser: baselineBrowser,
  },
  "company-queries-i": {
    sourceId: "1687",
    algorithm: "binary lifting ancestor jumps",
    strategy: "tree",
    oracle: "tests/tree-algorithms.test.ts:company-queries-i",
    edgeCases: "tests/tree-algorithms.test.ts:company-queries-i",
    browser: baselineBrowser,
  },
  "building-teams": {
    sourceId: "1668",
    algorithm: "BFS bipartite two-coloring",
    strategy: "bfs",
    oracle: "tests/graph-algorithms.test.ts:building-teams",
    edgeCases: "tests/graph-algorithms.test.ts:building-teams",
    browser: baselineBrowser,
  },
  "round-trip-ii": {
    sourceId: "1678",
    algorithm: "DFS active-ancestor cycle reconstruction",
    strategy: "dfs",
    oracle: "tests/graph-algorithms.test.ts:round-trip-ii",
    edgeCases: "tests/graph-algorithms.test.ts:round-trip-ii",
    browser: baselineBrowser,
  },
  "shortest-routes-ii": {
    sourceId: "1672",
    algorithm: "Floyd-Warshall all-pairs shortest paths",
    strategy: "shortest-path",
    oracle: "tests/graph-algorithms.test.ts:shortest-routes-ii",
    edgeCases: "tests/graph-algorithms.test.ts:shortest-routes-ii",
    browser: baselineBrowser,
  },
  "building-roads": {
    sourceId: "1666",
    algorithm: "DFS component leaders and minimum connecting roads",
    strategy: "dfs",
    oracle: "tests/graph-foundations.test.ts:building-roads",
    edgeCases: "tests/graph-foundations.test.ts:building-roads",
    browser: baselineBrowser,
  },
  "course-schedule": {
    sourceId: "1679",
    algorithm: "Kahn indegree topological sort",
    strategy: "topological-sort",
    oracle: "tests/graph-foundations.test.ts:course-schedule",
    edgeCases: "tests/graph-foundations.test.ts:course-schedule",
    browser: baselineBrowser,
  },
  "road-reparation": {
    sourceId: "1675",
    algorithm: "Kruskal minimum spanning tree with DSU",
    strategy: "dsu",
    oracle: "tests/graph-foundations.test.ts:road-reparation",
    edgeCases: "tests/graph-foundations.test.ts:road-reparation",
    browser: baselineBrowser,
  },
  "flight-routes-check": {
    sourceId: "1682",
    algorithm: "forward and reversed DFS strong connectivity",
    strategy: "dfs",
    oracle: "tests/graph-foundations.test.ts:flight-routes-check",
    edgeCases: "tests/graph-foundations.test.ts:flight-routes-check",
    browser: baselineBrowser,
  },
  "money-sums": {
    sourceId: "1745",
    algorithm: "0/1 subset-sum reachability DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:money-sums",
    edgeCases: "tests/dynamic-programming-problems.test.ts:money-sums",
    browser: baselineBrowser,
  },
  "two-sets-ii": {
    sourceId: "1093",
    algorithm: "half-sum subset-count DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:two-sets-ii",
    edgeCases: "tests/dynamic-programming-problems.test.ts:two-sets-ii",
    browser: baselineBrowser,
  },
  "increasing-subsequence": {
    sourceId: "1145",
    algorithm: "patience tails with lower bound",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:increasing-subsequence",
    edgeCases:
      "tests/dynamic-programming-problems.test.ts:increasing-subsequence",
    browser: baselineBrowser,
  },
  "rectangle-cutting": {
    sourceId: "1744",
    algorithm: "2D guillotine-cut DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:rectangle-cutting",
    edgeCases: "tests/dynamic-programming-problems.test.ts:rectangle-cutting",
    browser: baselineBrowser,
  },
  "array-description": {
    sourceId: "1746",
    algorithm: "adjacent-value 2D DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:array-description",
    edgeCases: "tests/dynamic-programming-problems.test.ts:array-description",
    browser: baselineBrowser,
  },
  "minimizing-coins": {
    sourceId: "1634",
    algorithm: "unbounded minimum-coin DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:minimizing-coins",
    edgeCases: "tests/dynamic-programming-problems.test.ts:minimizing-coins",
    browser: baselineBrowser,
  },
  "coin-combinations-i": {
    sourceId: "1635",
    algorithm: "ordered coin-sum DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:coin-combinations-i",
    edgeCases: "tests/dynamic-programming-problems.test.ts:coin-combinations-i",
    browser: baselineBrowser,
  },
  "coin-combinations-ii": {
    sourceId: "1636",
    algorithm: "unordered coin-sum DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:coin-combinations-ii",
    edgeCases:
      "tests/dynamic-programming-problems.test.ts:coin-combinations-ii",
    browser: baselineBrowser,
  },
  "removing-digits": {
    sourceId: "1637",
    algorithm: "digit-subtraction DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:removing-digits",
    edgeCases: "tests/dynamic-programming-problems.test.ts:removing-digits",
    browser: baselineBrowser,
  },
  "book-shop": {
    sourceId: "1158",
    algorithm: "0/1 knapsack DP",
    strategy: "dp",
    oracle: "tests/dynamic-programming-problems.test.ts:book-shop",
    edgeCases: "tests/dynamic-programming-problems.test.ts:book-shop",
    browser: baselineBrowser,
  },
  "grid-paths-i": {
    sourceId: "1638",
    algorithm: "right/down grid path DP",
    strategy: "generic",
    oracle: "tests/dynamic-programming-problems.test.ts:grid-paths-i",
    edgeCases: "tests/dynamic-programming-problems.test.ts:grid-paths-i",
    browser: baselineBrowser,
  },
  "maximum-subarray-sum": {
    sourceId: "1643",
    algorithm: "Kadane maximum suffix recurrence",
    strategy: "array",
    oracle: "tests/sorting-searching-problems.test.ts:maximum-subarray-sum",
    edgeCases: "tests/sorting-searching-problems.test.ts:maximum-subarray-sum",
    browser: baselineBrowser,
  },
  "stick-lengths": {
    sourceId: "1074",
    algorithm: "median absolute deviation",
    strategy: "sorting",
    oracle: "tests/sorting-searching-problems.test.ts:stick-lengths",
    edgeCases: "tests/sorting-searching-problems.test.ts:stick-lengths",
    browser: baselineBrowser,
  },
  "missing-coin-sum": {
    sourceId: "2183",
    algorithm: "sorted reachable-prefix greedy",
    strategy: "sorting",
    oracle: "tests/sorting-searching-problems.test.ts:missing-coin-sum",
    edgeCases: "tests/sorting-searching-problems.test.ts:missing-coin-sum",
    browser: baselineBrowser,
  },
  "collecting-numbers": {
    sourceId: "2216",
    algorithm: "consecutive-position descents",
    strategy: "array",
    oracle: "tests/sorting-searching-problems.test.ts:collecting-numbers",
    edgeCases: "tests/sorting-searching-problems.test.ts:collecting-numbers",
    browser: baselineBrowser,
  },
  playlist: {
    sourceId: "1141",
    algorithm: "last-seen sliding window",
    strategy: "sliding-window",
    oracle: "tests/sorting-searching-problems.test.ts:playlist",
    edgeCases: "tests/sorting-searching-problems.test.ts:playlist",
    browser: baselineBrowser,
  },
  "nearest-smaller-values": {
    sourceId: "1645",
    algorithm: "monotonic stack",
    strategy: "array",
    oracle: "tests/sorting-searching-problems.test.ts:nearest-smaller-values",
    edgeCases:
      "tests/sorting-searching-problems.test.ts:nearest-smaller-values",
    browser: baselineBrowser,
  },
  "subarray-sums-i": {
    sourceId: "1660",
    algorithm: "positive sliding window",
    strategy: "sliding-window",
    oracle: "tests/sorting-searching-problems.test.ts:subarray-sums-i",
    edgeCases: "tests/sorting-searching-problems.test.ts:subarray-sums-i",
    browser: baselineBrowser,
  },
  "subarray-sums-ii": {
    sourceId: "1661",
    algorithm: "prefix-frequency map",
    strategy: "range",
    oracle: "tests/sorting-searching-problems.test.ts:subarray-sums-ii",
    edgeCases: "tests/sorting-searching-problems.test.ts:subarray-sums-ii",
    browser: baselineBrowser,
  },
  "subarray-divisibility": {
    sourceId: "1662",
    algorithm: "prefix-remainder frequencies",
    strategy: "range",
    oracle: "tests/sorting-searching-problems.test.ts:subarray-divisibility",
    edgeCases: "tests/sorting-searching-problems.test.ts:subarray-divisibility",
    browser: baselineBrowser,
  },
  "weird-algorithm": {
    sourceId: "1068",
    algorithm: "odd/even recurrence",
    strategy: "generic",
    oracle: "tests/introductory-problems.test.ts:weird-algorithm",
    edgeCases: "tests/introductory-problems.test.ts:weird-algorithm",
    browser: baselineBrowser,
  },
  "missing-number": {
    sourceId: "1083",
    algorithm: "arithmetic sum difference",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:missing-number",
    edgeCases: "tests/introductory-problems.test.ts:missing-number",
    browser: baselineBrowser,
  },
  repetitions: {
    sourceId: "1069",
    algorithm: "run-length scan",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:repetitions",
    edgeCases: "tests/introductory-problems.test.ts:repetitions",
    browser: baselineBrowser,
  },
  permutations: {
    sourceId: "1070",
    algorithm: "parity construction",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:permutations",
    edgeCases: "tests/introductory-problems.test.ts:permutations",
    browser: baselineBrowser,
  },
  "bit-strings": {
    sourceId: "1617",
    algorithm: "modular doubling",
    strategy: "number-theory",
    oracle: "tests/introductory-problems.test.ts:bit-strings",
    edgeCases: "tests/introductory-problems.test.ts:bit-strings",
    browser: baselineBrowser,
  },
  "trailing-zeros": {
    sourceId: "1618",
    algorithm: "factor-of-five counting",
    strategy: "generic",
    oracle: "tests/introductory-problems.test.ts:trailing-zeros",
    edgeCases: "tests/introductory-problems.test.ts:trailing-zeros",
    browser: baselineBrowser,
  },
  "coin-piles": {
    sourceId: "1754",
    algorithm: "linear Diophantine invariant",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:coin-piles",
    edgeCases: "tests/introductory-problems.test.ts:coin-piles",
    browser: baselineBrowser,
  },
  "two-knights": {
    sourceId: "1072",
    algorithm: "combinatorial complement counting",
    strategy: "geometry",
    oracle: "tests/introductory-problems.test.ts:two-knights",
    edgeCases: "tests/introductory-problems.test.ts:two-knights",
    browser: baselineBrowser,
  },
  "two-sets": {
    sourceId: "1092",
    algorithm: "descending greedy partition",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:two-sets",
    edgeCases: "tests/introductory-problems.test.ts:two-sets",
    browser: baselineBrowser,
  },
  "number-spiral": {
    sourceId: "1071",
    algorithm: "square-layer parity formula",
    strategy: "array",
    oracle: "tests/introductory-problems.test.ts:number-spiral",
    edgeCases: "tests/introductory-problems.test.ts:number-spiral",
    browser: baselineBrowser,
  },
  "increasing-array": {
    sourceId: "1094",
    algorithm: "greedy monotone scan",
    strategy: "array",
    oracle: "tests/problem-certification.test.ts:increasing-array-oracle",
    edgeCases: "tests/code-runtime.test.ts",
    browser: baselineBrowser,
  },
  labyrinth: {
    sourceId: "1193",
    algorithm: "breadth-first search",
    strategy: "bfs",
    oracle: "tests/correctness.test.ts:labyrinth",
    edgeCases: "tests/simulation.test.ts",
    browser: baselineBrowser,
  },
  "message-route": {
    sourceId: "1667",
    algorithm: "breadth-first search",
    strategy: "bfs",
    oracle: "tests/correctness.test.ts:message-route",
    edgeCases: "tests/simulation.test.ts",
    browser: baselineBrowser,
  },
  "tree-diameter": {
    sourceId: "1131",
    algorithm: "two breadth-first searches",
    strategy: "tree",
    oracle: "tests/correctness.test.ts:tree-diameter",
    edgeCases: "tests/simulation.test.ts",
    browser: baselineBrowser,
  },
  "dice-combinations": {
    sourceId: "1633",
    algorithm: "one-dimensional dynamic programming",
    strategy: "dp",
    oracle: "tests/correctness.test.ts:dice-combinations",
    edgeCases: "tests/simulation.test.ts",
    browser: baselineBrowser,
  },
  "distinct-numbers": {
    sourceId: "1621",
    algorithm: "sort and scan",
    strategy: "sorting",
    oracle: "tests/representative-problems.test.ts:distinct-numbers",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "sum-of-two-values": {
    sourceId: "1640",
    algorithm: "sort and two pointers",
    strategy: "two-pointers",
    oracle: "tests/representative-problems.test.ts:sum-of-two-values",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "sliding-window-sum": {
    sourceId: "3220",
    algorithm: "sliding window",
    strategy: "sliding-window",
    oracle: "tests/representative-problems.test.ts:sliding-window-sum",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "factory-machines": {
    sourceId: "1620",
    algorithm: "binary search on answer",
    strategy: "binary-search",
    oracle: "tests/representative-problems.test.ts:factory-machines",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "static-range-sum": {
    sourceId: "1646",
    algorithm: "prefix sums",
    strategy: "range",
    oracle: "tests/representative-problems.test.ts:static-range-sum",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "dynamic-range-sum": {
    sourceId: "1648",
    algorithm: "Fenwick tree",
    strategy: "fenwick",
    oracle: "tests/representative-problems.test.ts:dynamic-range-sum",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "counting-rooms": {
    sourceId: "1192",
    algorithm: "depth-first flood fill",
    strategy: "dfs",
    oracle: "tests/representative-problems.test.ts:counting-rooms",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "shortest-routes-i": {
    sourceId: "1671",
    algorithm: "Dijkstra shortest path",
    strategy: "shortest-path",
    oracle: "tests/representative-problems.test.ts:shortest-routes-i",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  subordinates: {
    sourceId: "1674",
    algorithm: "tree postorder aggregation",
    strategy: "tree",
    oracle: "tests/representative-problems.test.ts:subordinates",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "road-construction": {
    sourceId: "1676",
    algorithm: "disjoint set union",
    strategy: "dsu",
    oracle: "tests/representative-problems.test.ts:road-construction",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "edit-distance": {
    sourceId: "1639",
    algorithm: "two-dimensional dynamic programming",
    strategy: "dp",
    oracle: "tests/representative-problems.test.ts:edit-distance",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "string-matching": {
    sourceId: "1753",
    algorithm: "Knuth-Morris-Pratt",
    strategy: "strings",
    oracle: "tests/representative-problems.test.ts:string-matching",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "chessboard-and-queens": {
    sourceId: "1624",
    algorithm: "backtracking",
    strategy: "backtracking",
    oracle: "tests/representative-problems.test.ts:chessboard-and-queens",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  exponentiation: {
    sourceId: "1095",
    algorithm: "binary exponentiation",
    strategy: "number-theory",
    oracle: "tests/representative-problems.test.ts:exponentiation",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
  "polygon-area": {
    sourceId: "2191",
    algorithm: "shoelace formula",
    strategy: "geometry",
    oracle: "tests/representative-problems.test.ts:polygon-area",
    edgeCases: baselineEdges,
    browser: baselineBrowser,
  },
};
