import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const mode = process.argv[2] ?? "status";
if (!["status", "verify", "release"].includes(mode))
  throw new Error("Use status, verify or release");
const pnpm = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
const files = [
  "tests/problem-certification.test.ts",
  "tests/lazy-problem-registry.test.ts",
  "tests/representative-problems.test.ts",
  "tests/correctness.test.ts",
  "tests/introductory-problems.test.ts",
  "tests/sorting-searching-problems.test.ts",
  "tests/dynamic-programming-problems.test.ts",
  "tests/graph-foundations.test.ts",
  "tests/graph-algorithms.test.ts",
  "tests/tree-algorithms.test.ts",
  "tests/range-algorithms.test.ts",
  "tests/string-algorithms.test.ts",
  "tests/dynamic-advanced.test.ts",
  "tests/dag-routes.test.ts",
  "tests/mathematics-advanced.test.ts",
  "tests/geometry-primitives.test.ts",
  "tests/range-wave-100.test.ts",
  "tests/tree-wave-100.test.ts",
  "tests/graph-wave-100.test.ts",
];
const result = spawnSync(pnpm, ["exec", "vitest", "run", ...files], {
  stdio: "inherit",
  shell: process.platform === "win32",
  env: { ...process.env, PROBLEMS_MODE: mode },
});
if (result.error) throw result.error;
if (result.status !== 0) {
  console.error("CSES evidence tests failed; no certified count is published.");
  process.exit(result.status ?? 1);
}
const report = JSON.parse(
  readFileSync("artifacts/problem-certificates/status.json", "utf8"),
);
if (mode === "status") {
  mkdirSync("docs/progress", { recursive: true });
  writeFileSync(
    "docs/progress/cses-status.json",
    JSON.stringify(report, null, 2) + "\n",
  );
  const rows = report.entries.map((item) =>
    [
      item.sourceId,
      item.title,
      item.category,
      item.algorithm || "—",
      item.renderer,
      item.choreography || "—",
      item.status,
    ]
      .map((value) => value.replaceAll("|", "\\|"))
      .join(" | ")
      .replace(/^/, "| ")
      .replace(/$/, " |"),
  );
  writeFileSync(
    "docs/CSES-CATALOG.md",
    [
      "# CSES catalog",
      "",
      "Generated by `pnpm problems:status` after the complete evidence suite passes. Source summaries and teaching material are original.",
      "",
      "| CSES ID | Problem | Category | Algorithm | Renderer | Choreography | Status |",
      "| --- | --- | --- | --- | --- | --- | --- |",
      ...rows,
      "",
    ].join("\n"),
  );
  const format = spawnSync(
    pnpm,
    [
      "exec",
      "prettier",
      "--write",
      "docs/CSES-CATALOG.md",
      "docs/progress/cses-status.json",
    ],
    { stdio: "inherit", shell: process.platform === "win32" },
  );
  if (format.error) throw format.error;
  if (format.status !== 0) process.exit(format.status ?? 1);
}
console.info(
  `CSES: ${report.uniqueRegistered} registered, ${report.certified} certified, ${report.partial} partial, ${report.failed.length} failed; release target ${report.target}.`,
);
console.info("Certified CSES IDs: " + report.certifiedIds.join(", "));
console.info("By category: " + JSON.stringify(report.byCategory));
console.info("By algorithm: " + JSON.stringify(report.byAlgorithm));
console.info("By renderer: " + JSON.stringify(report.byRenderer));
console.info("By choreography: " + JSON.stringify(report.byChoreography));
if (mode !== "status") {
  const browser = spawnSync(
    pnpm,
    ["exec", "playwright", "test", "tests/e2e/all-problem-routes.spec.ts"],
    { stdio: "inherit", shell: process.platform === "win32", env: process.env },
  );
  if (browser.error) throw browser.error;
  process.exitCode = browser.status ?? 1;
}
